services:
  clinic-stock-console:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_stock_console
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
